name: pytester-cov workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Install Python Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run linter on src directory
        run: |
          pylint --rcfile=pylintrc src
      - name: Run tests and coverage report
        run: |       
          coverage run --data-file tests/.coverage -m pytest -s
          coverage json --data-file tests/.coverage -o buf/tests/coverage.json
          coverage report --data-file tests/.coverage