name: CodeCov
jobs:
  codecov:
    runs-on: ubuntu-latest
    name: codecov
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m unittest
      - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2