name: run tests

on: [push]

jobs:
  pytest-run:
    runs-on: ubuntu-latest
    name: Pytest run
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: pytest-tests-run
        run: |
          pytest